name: Python Application

on:
  push:
    paths:
      - 'src/fetcher/btc_usd_fetcher.py'
      - 'tests/test_btc_usd_fetcher.py'
  pull_request:
    paths:
      - 'src/fetcher/btc_usd_fetcher.py'
      - 'tests/test_btc_usd_fetcher.py'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/fetcher/requirements.txt
        pip install flake8 pytest pytest-mock pytest-cov
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src/fetcher/btc_usd_fetcher.py tests/test_btc_usd_fetcher.py --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 src/fetcher/btc_usd_fetcher.py tests/test_btc_usd_fetcher.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest and coverage
      run: |
        PYTHONPATH=src pytest tests/test_btc_usd_fetcher.py --cov=src/fetcher --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true
