name: 'Terraform'
on:
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  AWS_REGION: us-east-1
  TF_WORKING_DIR: ./terraform
  TF_VERSION: 1.9.5
  TF_STATE_BUCKET: terraform-state-bucket-dsti
  TF_STATE_KEY: btc-usd-pipeline/terraform.tfstate
  TF_LOCK_TABLE: terraform-state-lock-table-dsti
  S3_BUCKET_NAME: terraform-state-bucket-dsti

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform-lint:
    name: 'Terraform Lint'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      with:
        terraform_version: ${{ env.TF_VERSION }}
    - name: Terraform Format
      run: |
        terraform fmt -recursive
        terraform fmt -check
    - name: tflint
      uses: terraform-linters/setup-tflint@v4
    - name: Run tflint
      run: tflint --recursive
      working-directory: ${{ env.TF_WORKING_DIR }}

  terraform-security-scan:
    name: 'Terraform Security Scan'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ${{ env.TF_WORKING_DIR }}

  terraform-plan:
    name: 'Terraform Plan'
    needs: [terraform-lint, terraform-security-scan]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.TF_WORKING_DIR }}
      
    # Check and Import pre-existing resources
    - name: Check and Import Pre-existing Resources
      run: |
        import_resource() {
          resource_type=$1
          resource_name=$2
          terraform_resource=$3
          provider_flag=$4
          region=$5
          
          if [ -n "$region" ]; then
            AWS_REGION_FLAG="--region $region"
          else
            AWS_REGION_FLAG=""
          fi
          
          if aws $AWS_REGION_FLAG $resource_type $resource_name > /dev/null 2>&1; then
            echo "Importing existing $resource_type: $resource_name"
            if [ -n "$provider_flag" ]; then
              terraform import $provider_flag $terraform_resource $resource_name
            else
              terraform import $terraform_resource $resource_name
            fi
          else
            echo "$resource_type $resource_name does not exist, skipping import"
          fi
        }
        
        # Import S3 buckets and their configurations
        buckets=(
          "central_logging_bucket:terraform-central-logging-bucket-dsti"
          "terraform_state_bucket:terraform-state-bucket-dsti"
          "replication_bucket:terraform-state-replication-bucket-dsti"
          "replication_logging_bucket:terraform-replication-logging-bucket-dsti"
        )
        
        for bucket_pair in "${buckets[@]}"; do
          IFS=':' read -r resource_name bucket_name <<< "$bucket_pair"
          provider_flag=""
          region=""
          if [[ "$bucket_name" == *"replication"* ]]; then
            provider_flag="-provider=aws.replication_region"
            region="eu-north-1"
          fi
          
          import_resource "s3api head-bucket --bucket" "$bucket_name" "aws_s3_bucket.$resource_name" "$provider_flag" "$region"
          import_resource "s3api head-bucket --bucket" "$bucket_name" "aws_s3_bucket_versioning.${resource_name}_versioning" "$provider_flag" "$region"
          import_resource "s3api head-bucket --bucket" "$bucket_name" "aws_s3_bucket_server_side_encryption_configuration.${resource_name}_encryption" "$provider_flag" "$region"
          import_resource "s3api head-bucket --bucket" "$bucket_name" "aws_s3_bucket_lifecycle_configuration.${resource_name}_lifecycle" "$provider_flag" "$region"
          import_resource "s3api head-bucket --bucket" "$bucket_name" "aws_s3_bucket_public_access_block.${resource_name}_public_access_block" "$provider_flag" "$region"
        done
        
        # Import S3 bucket logging configurations
        import_resource "s3api get-bucket-logging --bucket" "terraform-state-bucket-dsti" "aws_s3_bucket_logging.terraform_state_bucket_logging"
        import_resource "s3api get-bucket-logging --bucket" "terraform-state-replication-bucket-dsti" "aws_s3_bucket_logging.replication_bucket_logging" "-provider=aws.replication_region" "eu-north-1"
        
        # Import S3 bucket replication configuration
        import_resource "s3api get-bucket-replication --bucket" "terraform-state-bucket-dsti" "aws_s3_bucket_replication_configuration.terraform_state_bucket_replication"
        
        # Import IAM role and policy
        import_resource "iam get-role --role-name" "s3-replication-role" "aws_iam_role.replication_role"
        import_resource "iam get-role-policy --role-name s3-replication-role --policy-name" "replication_policy" "aws_iam_role_policy.replication_policy" "" "" "s3-replication-role:replication_policy"
        
        # Import KMS keys
        import_resource "kms describe-key --key-id" "$(terraform output -raw sns_encryption_key_arn)" "aws_kms_key.sns_encryption_key"
        import_resource "kms describe-key --key-id" "$(terraform output -raw sns_encryption_key_replication_arn)" "aws_kms_key.sns_encryption_key_replication" "-provider=aws.replication_region" "eu-north-1"
        
        # Import SNS topics
        import_resource "sns get-topic-attributes --topic-arn" "$(terraform output -raw central_logging_bucket_topic_arn)" "aws_sns_topic.central_logging_bucket_topic"
        import_resource "sns get-topic-attributes --topic-arn" "$(terraform output -raw terraform_state_bucket_topic_arn)" "aws_sns_topic.terraform_state_bucket_topic"
        import_resource "sns get-topic-attributes --topic-arn" "$(terraform output -raw replication_bucket_topic_arn)" "aws_sns_topic.replication_bucket_topic" "-provider=aws.replication_region" "eu-north-1"
        
        # Import ECR repository
        import_resource "ecr describe-repositories --repository-names" "btc-usd-fetcher" "aws_ecr_repository.btc_usd_fetcher"
        
        # Import DynamoDB table
        import_resource "dynamodb describe-table --table-name" "terraform-state-lock-table-dsti" "aws_dynamodb_table.terraform_state_lock"

      working-directory: ${{ env.TF_WORKING_DIR }}
      
    - name: Terraform Validate
      run: terraform validate
      working-directory: ${{ env.TF_WORKING_DIR }}
    - name: Terraform Plan
      run: |
        TF_LOG=TRACE terraform plan \
          -out=tfplan
      working-directory: ${{ env.TF_WORKING_DIR }}
    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v4.4.0
      with:
        name: tfplan
        path: ${{ env.TF_WORKING_DIR }}/tfplan
        retention-days: 5

  terraform-apply:
    name: 'Terraform Apply'
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: production
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      # Remove any existing plan file to avoid issues
      - name: Remove Old Plan File
        run: |
          rm -f ${{ env.TF_WORKING_DIR }}/tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}

      # Regenerate the plan to ensure it matches the current state
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        run: |
          TF_LOG=TRACE terraform apply \
            -auto-approve tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Output
        if: success()
        run: |
          terraform output
        working-directory: ${{ env.TF_WORKING_DIR }}
